# Generated by Django 5.1.2 on 2024-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("species", models.CharField(max_length=255)),
                ("watering_frequency_days", models.PositiveIntegerField()),
                ("last_watered_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
